### ISSUE TITLE
PageWithHeader fix 1px transparent before header that shows content underneath once scrolling.

### ISSUE THREAD

**Issue by agustif** [jxom/bumbag-ui#20]
I can see 1px transparent line before header/TopNav
```index.ts
<PageWithHeader style={{marginTop: "-1px"}}
  sticky
...
  ```

I can fix it adding this.

**Comment by jxom** [comment]
Hmm. I can't seem to reproduce this one in Playroom. Can you help me out?

https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIA8AFAhgcxgdQJYBcALACRjVgCcAdAOwAI6AjNMAawwogFcaoBhCABsIFALxUQFGFAm0GhMpVHAkAIQgAPAHwAVQrgDOdQ3TR0DuWMwpIA9Ou0BfOefy42AT1paXpQcLoAdxFBGXo6JEYKOlsfcL8A4IpQl0jo2N8YfwggkLCGNJi4hgScpJTwwoz4rMS81KiiulLc5PyIxtjm2rL6ys6tbuzWioKBobq2hvTBlvL2qtmekYWBzOH56aL1ydGOmZ3eqf6Dmo2%2BsdOS5c2TprmL-fubx8WJo723h%2BPL5-Ofp5db6fNZnXarK7vFZbarXf4gyHAiHbMEfZFAl4Ar6YhF-cEwpbw9GE-F3DFEgmHaFk4pQ26-WF016guGkhm0pEEplY8acmnc3HktmAklorl89lU%2BkiqXMxE44mynnyin8iUigXEzXihU61Xs7U0pWCjm6o2o6mSi3SxbGrXq7H6jUO3lmg0umaGq12dBYPBEUjkGAUOIgRxAA

**Comment by agustif** [comment]
I think it was some other code adding the bug can close!

**Comment by agustif** [comment]
> I think it was some other code adding the bug can close!

OK I was wrong, still there and has something to do with my ccode. Here's same bug on playground.

https://bumbag.style/playroom/#?code=N4Igxg9gJgpiBcIAESA8AFAhgcxgdQEsAXACwAkZNYAnAHQDsUBnIgsAawE8GUTKaAvMB4o0AFQgAHAHKYAbgD4Ro8VNlyAdAGUYYVhHpLGK0agkz5GgJJEYAWyQlqMAGYDaIEkSKSm8APT%2BAEYArnZBOBosnAA2MB5ILgZEeDAE2F7uIEz2BEEQMVAeRiYmqFZ2ODBITNRgWf4xENgQGpL02Al86ZkeACx9kgAeCf4lpWj%2B5urWtnbjpWZqljb2ChNoADIE9OyOzm4e-sXKE6iYCmQQdjCo-henKnfbuwp30ytzC2Ufmqvzj1MLz2TlcDUw%2BRCRBOxg25wUAEFIUQ7g9YWV-MC3lNln8vgwCeinr9ZmtAShUMD9mCjiEctQmDCNhSLgBVelMJDbFio75PTE7djYkn-PmmEX4olAwXUw4ge6SAj%2BOkwBlMxZsjlIBHoKy88lwgWvd640kAqUUiVki1bGWguX%2BJLOOSq9Vwi4AMQgztV%2Bptz0FYopOIseOtBqWobNQdtu1lDXoBgAtDAhgQWDtOiAY-DpAYkABRNMZjpILC4P2GrERkMzUWEwmLWuWHR6AgGMWRmat-SMSrUbA7ABKPSIWUqACtvUmAKxun6m%2Bs2ikAIShRHzckw1AImHoY48GQgLASkkwcW8MCykh3-e42a06UYIUkdzX3g7Nat5rh35jq-XfMzwvWxr1vbd7wUTZmh2N9AMML9F0lJsSR7dsEPRE1Q3GABfER8moQQPFgFxMBCGJoRAEQIBdagd1gJghGAMsqkIUgKCoVV4CQZjojiPweKQCIcm45i7B2ChR24gByEJ6ByIhpKQHDlNUnC8Iw1cICGJAzygKBM3HTAp2oJMACZigoGImkSahriQGJME4CAoTfbSjBEVADMUBhMCYKA-IC-zTkCwKQv8zBTigJhIvRIKinRMK4tCmKIrShKVBSjLRFCqKYqipLMuC5K0qywqcvS8KAry2KVHiqqCtK9LypQLKqtq0Roo6lB6sS4q6pSsr%2Boq3qiuquL8pK7LWuGnrBua2akDavrxrqyaBsWlqkHivyhumpbKpW7rtvWzqtq2nbUsu-blrG46usam7Fsuvb2s2iKasehqpt2hantGkb7tOub3v2l6-re-6gfu87nvm67Ifaz6pu%2Bjagteo7Qehr6Vse36EcxqHkbR1Gzqagm7qx4myf%2BvGrtuwGqYmmHQbpjHKaJ5mcbGtmIcJpGuZR3Gfvpw6OYFtaWdpkX2cZznJe5kbeYpuWJc64HtthsH4YZmaAb17GhZ5mW%2BfFo7qZB6W0fx3WDv1u3DZJ4XrdF%2B3bdywWneNl3ZYNpmFaNpWRdOVAkggWxqE7JwkDGQFUCYM9DCsaSHD4ZwkA3GoiCcpAAAovXD1UAEo7gTvdvjuMOI-GO5vJr-xy3wYhyH4VUFBAHCgA

**Comment by agustif** [comment]
It seems some Interaction with Top.Nav?

**Comment by agustif** [comment]
I think this is some interaction with my code as I can't reproduce it on playground.

I'm ok with my hack -1px for now, so maybe we can close this for now.

**Comment by agustif** [comment]
Still happening with Safari on Mac, doesnt happen with chrome,any ideas?
